//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_SE_12.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string ID_Account { get; set; }
        public string Login { get; set; }
        public string PassWord { get; set; }
        public string ID_Type { get; set; }
    
        public virtual Type_Account Type_Account { get; set; }
        public virtual User User { get; set; }
    }
}
