//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_SE_12.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Order
    {
        public int ID_DetailOrder { get; set; }
        public string ID_Items { get; set; }
        public int Price { get; set; }
        public string Amount { get; set; }
        public System.DateTime Order_Time { get; set; }
        public string ID_Order { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
