//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_SE_12.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Account
    {
        public string ID_Type { get; set; }
        public string Access { get; set; }
    }
}
